### ISSUE TITLE
Unable to move location of Observation from Edit window

### ISSUE THREAD

**Issue by cwas** [ngageoint/mage-ios#26]
Unable to change the location of the marker from the new observation edit window.

Steps:
From main map > New > click the Latitude/Longitude > moving the map also moves the marker so it's not possible to change the location of the marker.

**Comment by newmanw** [comment]
57890989202db9c52b0c5e1760d8f8ab047aeb2b

**Comment by newmanw** [comment]
iOS out of the box default is to long press the marker.  The marker will animate above your finger and you can then drag it at that point.  Release and the marker will drop.  I have added a prompt on the edit location navbar to make this more clear.
