### ISSUE TITLE
startup hang

### ISSUE THREAD

**Issue by restjohn** [ngageoint/mage-ios#34]
When I launched MAGE, it hung on the blank blue startup screen displaying only the server URL (magedemo in my case).  I quite the app, then later launched it again and it behaved normally, displaying the sign-in options.

**Comment by newmanw** [comment]
This was caused by a problem with the client failing to get a response from the server.  You should now see a spinner indicating the client is trying to communicate with the server, 2af85f6f282eace49ddf90b16d51b53f96a2dfbc
