### ISSUE TITLE
unresponsive Use Photo button

### ISSUE THREAD

**Issue by restjohn** [ngageoint/mage-ios#35]
When creating a new observation, I used the camera button to launch the camera and take a photo to attach to the observation.  After tapping the shutter button, MAGE displays the screen with the photo and the "Retake" and "Use Photo" options.  When I tapped the "Use Photo" button, the app did not give me any indication it received my input and would take a few seconds to return to the observation form.  I was not able to tell when I had successfully chosen the image for the observation.

**Comment by danielbarela** [comment]
This has been fixed.
