### ISSUE TITLE
semi-crash after event selection

### ISSUE THREAD

**Issue by restjohn** [ngageoint/mage-ios#36]
After launching MAGE, signing in with Google, and selecting my event, MAGE transitioned to the map view, showed it for a split second, then appeared to crash.  Specifically, my phone returned to the home screen.  When I double-tapped the home button, MAGE was still in the list of running apps, and I was able to return to MAGE by tapping its screenshot in the app list.

**Comment by newmanw** [comment]
Any crash logs?

**Comment by newmanw** [comment]
This is caused by the objective-zip library throwing an uncaught exception when the icons archive failed to extract to the local file system.
